# LODING NUMPY

In [1]:
import numpy as np
np.__version__

'1.24.3'

In [4]:
x=np.arange(10)
print(x)
type(x)

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [6]:
import numpy as np
arr=np.array([[10,20,30,40],[50,60,70,80],[12,23,43,54],[56,76,87,98]])
print(arr)
print("sum=",np.sum(arr))
type(arr)

[[10 20 30 40]
 [50 60 70 80]
 [12 23 43 54]
 [56 76 87 98]]
sum= 809


numpy.ndarray

In [7]:
import numpy as np
arr=np.array([[10,20,30,40],[50,60,70,80],[12,23,43,54],[56,76,87,98]])
print(arr)
print("sum=",np.sum(arr))
type(arr)

[[10 20 30 40]
 [50 60 70 80]
 [12 23 43 54]
 [56 76 87 98]]
sum= 809


numpy.ndarray

In [8]:
arr1=np.array([[[[1,2,3],(4,5,6),[23,11,24]],[[1,5,4],(7,8,9),[25,12,16]]],[[[23,84,55],[54,52,12],[32,25,63]],[[12,31,42],[45,42,9],[71,19,26]]]])
print(arr1)
print(arr1[0,1,1,0])
print(arr1.ndim)
print(arr1[0,-1,1,2]+arr1[1,0,0,1])
print(arr1[-1,0,1,0]+arr1[1,0,-1,2])
print(arr1.shape)

[[[[ 1  2  3]
   [ 4  5  6]
   [23 11 24]]

  [[ 1  5  4]
   [ 7  8  9]
   [25 12 16]]]


 [[[23 84 55]
   [54 52 12]
   [32 25 63]]

  [[12 31 42]
   [45 42  9]
   [71 19 26]]]]
7
4
93
117
(2, 2, 3, 3)


# PANDAS

In [10]:
import pandas as pd
n7=pd.date_range('20230901',periods=27)
print(n7)

DatetimeIndex(['2023-09-01', '2023-09-02', '2023-09-03', '2023-09-04',
               '2023-09-05', '2023-09-06', '2023-09-07', '2023-09-08',
               '2023-09-09', '2023-09-10', '2023-09-11', '2023-09-12',
               '2023-09-13', '2023-09-14', '2023-09-15', '2023-09-16',
               '2023-09-17', '2023-09-18', '2023-09-19', '2023-09-20',
               '2023-09-21', '2023-09-22', '2023-09-23', '2023-09-24',
               '2023-09-25', '2023-09-26', '2023-09-27'],
              dtype='datetime64[ns]', freq='D')


In [11]:
s1=pd.Series(('apple','orange','guava','mango'))
print(s1)

0     apple
1    orange
2     guava
3     mango
dtype: object


In [18]:
df=pd.read_csv("C:/Documents/data.csv")
df

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [19]:
import pandas as pd
import numpy as np
colors=['red','orange','yellow','green','blue','indigo','violet']
sub_colors=colors[1:4]
print(sub_colors)

['orange', 'yellow', 'green']


In [20]:
colors=['red','orange','yellow','green','blue','indigo','violet']
sub_colors=colors[::2]
print(sub_colors)

['red', 'yellow', 'blue', 'violet']


In [21]:
colors=['red','orange','yellow','green','blue','indigo','violet']
reversed_colors=colors[::-1]
print(reversed_colors)

['violet', 'indigo', 'blue', 'green', 'yellow', 'orange', 'red']


In [22]:
numbers=[1,2,3,4,5]
sq=[numbers**2 for numbers in numbers]
print(sq)

[1, 4, 9, 16, 25]


In [23]:
df = pd.read_csv("C:\Documents\Toyota (1).csv")
print(df)
print(df.info())

      Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
0              0  13500  23.0  46986   Diesel   90       1.0          0  2000   
1              1  13750  23.0  72937   Diesel   90       1.0          0  2000   
2              2  13950  24.0  41711   Diesel   90       NaN          0  2000   
3              3  14950  26.0  48000   Diesel   90       0.0          0  2000   
4              4  13750  30.0  38500   Diesel   90       0.0          0  2000   
...          ...    ...   ...    ...      ...  ...       ...        ...   ...   
1431        1431   7500   NaN  20544   Petrol   86       1.0          0  1300   
1432        1432  10845  72.0     ??   Petrol   86       0.0          0  1300   
1433        1433   8500   NaN  17016   Petrol   86       0.0          0  1300   
1434        1434   7250  70.0     ??      NaN   86       1.0          0  1300   
1435        1435   6950  76.0      1   Petrol  110       0.0          0  1600   

      Doors  Weight  
0    

# ARRAY AGGREATION FUN,USING MAP,FILTER,REDUCE AND LAMBDA

In [38]:
import pandas as pd
import numpy as np
df=pd.read_csv("C:/Documents/data.csv")
#df
#df.info()
#df.shape
#df.head()
#df.head(7)
#df.tail()
#df.tail(7)
#df.keys()
#df.index
#df.columns
#df.describe()
#df.size
#df.memory_usage()
#print(df.ndim)
#df.agg(['sum','min'])

Make   Model  Year                Engine Fuel Type  Engine HP  \
11907    Acura     ZDX  2011     premium unleaded (required)      300.0   
11908    Acura     ZDX  2011     premium unleaded (required)      300.0   
11909    Acura     ZDX  2012     premium unleaded (required)      300.0   
11910    Acura     ZDX  2012     premium unleaded (required)      300.0   
11911    Acura     ZDX  2012     premium unleaded (required)      300.0   
11912    Acura     ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln  Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
11907               6.0         AUTOMATIC    all wheel drive              4.0   
11908               6.0         AUTOMATIC    all wheel drive              4.0   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                  Market Category Vehicle Size  Vehicle Style  highway MPG  \
11907  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23   
11908  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23   
11909  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23   
11910  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23   
11911  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23   
11912  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23   
11913                      Luxury      Midsize          Sedan           26   

       city mpg  Popularity   MSRP  
11907        16         204  56570  
11908        16         204  50520  
11909        16         204  46120  
11910        16         204  56670  
11911        16         204  50620  
11912        16         204  50920  
11913        17          61  28995

In [39]:
import pandas as pd
import numpy as np
n2=pd.Series({"jan":31,"feb":28,"mar":31,"apr":30,"may":31,"jun":30,"jul":31,"aug":31,"sep":30,"oct":31,"nov":30,"dec":31})
print(n2)

jan    31
feb    28
mar    31
apr    30
may    31
jun    30
jul    31
aug    31
sep    30
oct    31
nov    30
dec    31
dtype: int64


In [40]:
n3=pd.date_range('20230901',periods=35)
print(n3)

DatetimeIndex(['2023-09-01', '2023-09-02', '2023-09-03', '2023-09-04',
               '2023-09-05', '2023-09-06', '2023-09-07', '2023-09-08',
               '2023-09-09', '2023-09-10', '2023-09-11', '2023-09-12',
               '2023-09-13', '2023-09-14', '2023-09-15', '2023-09-16',
               '2023-09-17', '2023-09-18', '2023-09-19', '2023-09-20',
               '2023-09-21', '2023-09-22', '2023-09-23', '2023-09-24',
               '2023-09-25', '2023-09-26', '2023-09-27', '2023-09-28',
               '2023-09-29', '2023-09-30', '2023-10-01', '2023-10-02',
               '2023-10-03', '2023-10-04', '2023-10-05'],
              dtype='datetime64[ns]', freq='D')


In [41]:
s=pd.Series([1,2,5,np.nan,6])
print(s)

0    1.0
1    2.0
2    5.0
3    NaN
4    6.0
dtype: float64


# CREATING A DATAFRAME

In [42]:
import pandas as pd
import numpy as np
students_data={
    'name':['vicky','venky','nihar'],
    'reg_no':['183cs21042','183cs21044','183cs21028'],
    'address':['rammurthynagar','ramnagar','rmnagar']
}
students_data=pd.DataFrame(data=students_data,index=[1,2,3])
print(students_data)

    name      reg_no         address
1  vicky  183cs21042  rammurthynagar
2  venky  183cs21044        ramnagar
3  nihar  183cs21028         rmnagar


In [49]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
df_data={
    'FirsrName':['Aryan','Rohan','Riya','Yash','Siddhant'],
    'LastName':['Singh','Agarwal','Shah','Bhatia','Khanna'],
    'Type':['Full-Time-Employee','Intem','Full-Time-Employee','Part-Time-Employee','Full-Time-Employee'],
    'Department':['Administration','Technical','Administration','Technical','Administration'],
    'YoE':['2','3','5','7','6'],
    'Salary':['20000','5000','10000','10000','20000']
}
df_data=pd.DataFrame(data=df_data,index=[1,2,3,4,5])
df_data
#pivot=df_data.pivot_table(index =['FirsrName'],
#                          values =['Salary'],
#                          aggfunc ='sum')
#print(pivot)

FirsrName LastName                Type      Department YoE Salary
1     Aryan    Singh  Full-Time-Employee  Administration   2  20000
2     Rohan  Agarwal               Intem       Technical   3   5000
3      Riya     Shah  Full-Time-Employee  Administration   5  10000
4      Yash   Bhatia  Part-Time-Employee       Technical   7  10000
5  Siddhant   Khanna  Full-Time-Employee  Administration   6  20000

In [53]:
import pandas as pd 
from functools import reduce
House_Predection1=pd.DataFrame({
    'SizeOfHouse':['20*20','20*30','30*40','40*20','40*50','50*20','50*30','60*30','60*20','60*60'],
    'Price':[ 2000000,340500,100000,400500,40000050,50005000,5003009,600500,6029390,601905000],
    'Gender':['male','male','female','male','female','female','female','male','male','female'],
    'GenderInNumber':[0,0,1,0,1,1,1,0,0,1],
    'Occupation':['Computer Software Engineers','Chemical Engineer','Newspaper Editor','Medical Secretary','Math Professor','Radio & TV Sports Announcer','Real Estate Sales Agents','Fashion Designer','Food & Drug Inspector','Industrial Designer'],
    'Age':['24','25','30','40','45','52','43','38','27','54'],
    'TypesOfHouses':['Apartment','Farmhouse','Farmhouse','Farmhouse','Apartment','Farmhouse','Apartment','Apartment','Apartment','Farmhouse',],
    'NoOfRoomsInHouse':['1','70','1','3','50','1','80','80','1','2']
},index=[1,2,3,4,5,6,7,8,9,10])
print(House_Predection1)
print("mapping")
def greatest_than(n):
    return n>340500
print(House_Predection1['TypesOfHouses'].map({'Apartment':'0','Farmhouse':'1'}))
#filtering=list(filter(lambda x:greater_than(x),df['Price']))
#print(filtering)

   SizeOfHouse      Price  Gender  GenderInNumber  \
1        20*20    2000000    male               0   
2        20*30     340500    male               0   
3        30*40     100000  female               1   
4        40*20     400500    male               0   
5        40*50   40000050  female               1   
6        50*20   50005000  female               1   
7        50*30    5003009  female               1   
8        60*30     600500    male               0   
9        60*20    6029390    male               0   
10       60*60  601905000  female               1   

                     Occupation Age TypesOfHouses NoOfRoomsInHouse  
1   Computer Software Engineers  24     Apartment                1  
2             Chemical Engineer  25     Farmhouse               70  
3              Newspaper Editor  30     Farmhouse                1  
4             Medical Secretary  40     Farmhouse                3  
5                Math Professor  45     Apartment               50  
6 

In [55]:
import pandas as pd
import numpy as np
str='abcdeabcdeaabbbccddeebacdeabbbaabebdbadabdbedaebbadebadeebadefffadebfaeedbfffedfdbddddebdee'
list1=list(str)
print(list1)
series=pd.Series(list1).value_counts()
print(series.to_dict())
new_dict={
    'char':series.to_dict(),
    'occurance':series.to_dict()
}
df=pd.DataFrame(data=new_dict,index=[1,2,3,4,5,6])
print(df)
#print(pd.pivot_table(df,index=['char']))

['a', 'b', 'c', 'd', 'e', 'a', 'b', 'c', 'd', 'e', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'd', 'e', 'e', 'b', 'a', 'c', 'd', 'e', 'a', 'b', 'b', 'b', 'a', 'a', 'b', 'e', 'b', 'd', 'b', 'a', 'd', 'a', 'b', 'd', 'b', 'e', 'd', 'a', 'e', 'b', 'b', 'a', 'd', 'e', 'b', 'a', 'd', 'e', 'e', 'b', 'a', 'd', 'e', 'f', 'f', 'f', 'a', 'd', 'e', 'b', 'f', 'a', 'e', 'e', 'd', 'b', 'f', 'f', 'f', 'e', 'd', 'f', 'd', 'b', 'd', 'd', 'd', 'd', 'e', 'b', 'd', 'e', 'e']
{'b': 22, 'd': 21, 'e': 19, 'a': 16, 'f': 8, 'c': 5}
   char  occurance
1   NaN        NaN
2   NaN        NaN
3   NaN        NaN
4   NaN        NaN
5   NaN        NaN
6   NaN        NaN
